# 数据源配置
spring:
  datasource:
    druid:
      # 初始连接数
      initialSize: 5
      # 最小连接池数量
      minIdle: 10
      # 最大连接池数量
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      # 配置一个连接在池中最大生存的时间，单位是毫秒
      maxEvictableIdleTimeMillis: 900000
      # 配置检测连接是否有效
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      webStatFilter:
        enabled: true
      statViewServlet:
        enabled: true
        # 设置白名单，不填则允许所有访问
        allow:
        url-pattern: /druid/*
        # 控制台管理用户名和密码
        login-username: 1
        login-password: 1
      filter:
        stat:
          enabled: true
          # 慢SQL记录
          log-slow-sql: true
          slow-sql-millis: 5000
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true
    #    driver-class-name: com.mysql.jdbc.Driver
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/vboot-java?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC&nullCatalogMeansCurrent=true
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: true
  banner:
    location: classpath:config/banner.txt
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

ldap:
  url:
  base:
  userDn:
  userPwd:
  referral:
  domainName:


logging.config: classpath:config/logback.xml


zsvg:
  jwt:
    header: Authorization
    prefix: "Bearer "
    #生成accessToken用的key
    akey: 6EtRVaDRFyIe5pBlBh1p6dRD+fLA5phPMyEeVkaNcEMUcpvQwZtGNby24TzuTZ4OBuXTYUaWgZqsRwROg1XWFA==
    #生成refreshToken用的key
    rkey: W3UZyVu0VQCGMRPvU11CqDovDUku3XASJlXLu0zFZdvUyAvXoEVrumKnz1DSBJ4O5l49Mi2Hesx7Kct4UPTL9g==
    #accessToken过期时间 此处单位秒 ，默认8小时 28800
    atime: 28800
    #accessToken过期时间 此处单位秒 ，默认30天 3456000
    rtime: 3456000
  #    # 在线用户key
  #    online-key: online-token-
  #    # 验证码
  #    code-key: code-key-
  #    # token 续期检查时间范围（默认30分钟，单位毫秒），在token即将过期的一段时间内用户操作了，则给用户的token续期
  #    detect: 1800000
  #    # 续期时间范围，默认1小时，单位毫秒
  #    renew: 3600000



